# Euler 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [1]:
### Using a while loop
LIMIT = 1000
total = 0
n = 1
while n < LIMIT:
    if n % 3 == 0 or n % 5 == 0:
        total += n
    n += 1
print(total)

233168

In [0]:
### Using range() and for loop
LIMIT = 1000
total = 0
for n in range(LIMIT):
    if n % 3 == 0 or n % 5 == 0:
        total += n
print(total)

In [0]:
### Using a function with while
def select(x):
    return x % 3 == 0 or x % 5 == 0

LIMIT = 1000
total = 0
n = 1
while n < LIMIT:
    if select(n):
        total += n
    n += 1
print(total)

In [0]:
### Using a function with for
def select(x):
    return x % 3 == 0 or x % 5 == 0
LIMIT = 1000
total = 0
for n in range(LIMIT):
    if select(n):
        total += n
print(total)

In [0]:
### Using filter with lambda
LIMIT = 1000
sum(filter(lambda x: x % 3 == 0 or x % 5 == 0, range(LIMIT)))

In [0]:
### Using filter with function
def select(x):
    return x % 3 == 0 or x % 5 == 0
LIMIT = 1000
sum(filter(select, range(LIMIT)))

In [0]:
### Using list comprehensions
LIMIT = 1000
sum([x for x in range(LIMIT) if x % 3 == 0 or x % 5 == 0])

In [0]:
### Using just ranges
LIMIT = 1000
sum(range(3, LIMIT, 3)) + sum(range(5, LIMIT, 5)) - sum(range(15, LIMIT, 15))

In [0]:
### Using sets
LIMIT = 1000
sum(set(range(3, LIMIT, 3)) | set(range(5, LIMIT, 5)))